/**
 * Create and upload a demo workflow to the database
 *
 * This demonstrates how to programmatically create workflows
 */

import { randomUUID } from 'crypto';
import { postgresDb } from '../src/lib/db';
import { workflowsTablePostgres } from '../src/lib/schema';

async function createDemoWorkflow() {
  // You'll need to replace this with an actual user ID from your database
  const userId = process.argv[2];

  if (!userId) {
    console.error('Usage: npx tsx scripts/create-demo-workflow.ts <userId>');
    console.error('\nTo get your user ID, run:');
    console.error('  npx drizzle-kit studio');
    console.error('Then open the browser, go to "users" table, and copy your user ID');
    process.exit(1);
  }

  if (!postgresDb) {
    throw new Error('Database not initialized');
  }

  const workflowId = randomUUID();

  const workflow = {
    id: workflowId,
    userId,
    organizationId: null,
    name: 'Daily Tech News Digest',
    description: 'Fetches latest tech news from RSS feeds, formats them nicely, and can send via email or Slack',
    prompt: 'Create a workflow that fetches the latest tech news from Hacker News RSS feed, extracts the top 5 items, formats them into a nice digest, and logs the result',

    config: {
      steps: [
        {
          id: 'fetch-hn-feed',
          module: 'utilities.rss.parseFeed',
          inputs: {
            url: 'https://news.ycombinator.com/rss'
          },
          outputAs: 'hnFeed'
        },
        {
          id: 'get-top-5',
          module: 'utilities.array.slice',
          inputs: {
            array: '{{hnFeed.items}}',
            start: 0,
            end: 5
          },
          outputAs: 'topStories'
        },
        {
          id: 'format-digest',
          module: 'utilities.string.template',
          inputs: {
            template: `# 🚀 Daily Tech News Digest

{{#each topStories}}
{{@index}}. **{{this.title}}**
   🔗 {{this.link}}
   📅 {{this.pubDate}}

{{/each}}

---
Generated by b0t workflow automation`,
            data: {
              topStories: '{{topStories}}'
            }
          },
          outputAs: 'digest'
        },
        {
          id: 'log-result',
          module: 'utilities.console.log',
          inputs: {
            message: '{{digest}}'
          }
        }
      ]
    },

    trigger: {
      type: 'manual' as const,
      config: {}
    },

    status: 'active'
  };

  // Insert the workflow
  await postgresDb.insert(workflowsTablePostgres).values({
    id: workflow.id,
    userId: workflow.userId,
    organizationId: workflow.organizationId,
    name: workflow.name,
    description: workflow.description,
    prompt: workflow.prompt,
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    config: JSON.stringify(workflow.config) as any,
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    trigger: JSON.stringify(workflow.trigger) as any,
    status: workflow.status,
  });

  console.log('✅ Demo workflow created successfully!');
  console.log(`\nWorkflow ID: ${workflowId}`);
  console.log(`Name: ${workflow.name}`);
  console.log(`\nYou can now:`);
  console.log(`1. View it in the dashboard: http://localhost:3000/dashboard/workflows`);
  console.log(`2. Run it manually from the UI`);
  console.log(`3. Or trigger it via API:`);
  console.log(`   curl -X POST http://localhost:3000/api/workflows/${workflowId}/execute`);

  process.exit(0);
}

createDemoWorkflow().catch((error) => {
  console.error('❌ Failed to create demo workflow:', error);
  process.exit(1);
});
